import {default as MirageMarkdown} from './markdown/markdown'
export { default as DefaultAddress } from './address/DefaultAddress'
export { default as CustomerQuotes } from './customerQuotes/customerQuotes'
export { default as PressQuotes } from './pressQuotes/pressQuotes'
export { MirageMarkdown }
export * from './inputs'
export { default as DefaultPayment } from './payment/DefaultPayment'
export * from './sections'
export * from './social-media'
export * from './video'
export * from './aboutUs'
