export { default as DefaultAddress } from './address/DefaultAddress'
export { default as CustomerQuotes } from './customerQuotes/customerQuotes'
export * from './inputs'
export * from './link'
export { default as DefaultPayment } from './payment/DefaultPayment'
export * from './sections'
export * from './social-media'
export * from './video'
